import argparse
import fnmatch
import json
import sys
import traceback
from datetime import datetime, timezone
from pathlib import Path

from .cases import find_case, load_cases
from .config import Config, detect_mpi_preflags


def _cmake_quote(s: str) -> str:
    # Semicolons are left alone so "a;b" stays a CMake list (LABELS, FIXTURES_*).
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def cmd_configure(a) -> int:
    features = [f for f in a.features.split(",") if f]
    cfg = Config(
        sw4=a.sw4, precision=a.precision, features=features, source_dir=a.source_dir,
        out_dir=a.out_dir, mpiexec=a.mpiexec, numproc_flag=a.numproc_flag,
        mpi_preflags=detect_mpi_preflags(a.mpiexec) + [f for f in a.mpi_preflags.split(";") if f],
        uv=a.uv, peer_out_dir=a.peer_out_dir or None, peer_precision=a.peer_precision or None,
    )
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    cfg.save(Path(a.out))
    return 0


def cmd_cmake(a) -> int:
    """Emit add_test() calls for every case runnable in this build."""
    cfg = Config.load(a.config)
    project = Path(__file__).resolve().parents[2]  # tests/harness
    base = [cfg.uv, "run", "--quiet", "--frozen", "--project", str(project), "sw4test"]
    cfg_args = ["--config", str(Path(a.config).resolve())]
    lines = ["# Generated by `sw4test cmake`; do not edit.\n"]
    n_tests = 0
    skipped = []
    for case in load_cases(cfg.cases_dir):
        missing = [f for f in case.requires if f not in cfg.features]
        if missing:
            skipped.append(f"{case.id} (needs {','.join(missing)})")
            continue
        if cfg.precision not in case.precisions:
            skipped.append(f"{case.id} (not run in {cfg.precision})")
            continue
        for run in case.runs.values():
            name = f"{case.id}:run:{run.name}"
            cmd = " ".join(_cmake_quote(x) for x in [*base, "run", *cfg_args, case.id, run.name])
            labels = ";".join([run.tier, *case.labels, "run"])
            lines.append(f"add_test(NAME {_cmake_quote(name)} COMMAND {cmd})\n")
            lines.append(
                f"set_tests_properties({_cmake_quote(name)} PROPERTIES"
                f" LABELS {_cmake_quote(labels)}"
                f" PROCESSORS {run.ranks * run.threads}"
                f" TIMEOUT {run.timeout}"
                f" FIXTURES_SETUP {_cmake_quote(case.id + ':' + run.name)}"
                + (f" FIXTURES_REQUIRED {_cmake_quote(';'.join(case.id + ':' + a for a in run.after))}" if run.after else "")
                + ")\n")
            n_tests += 1
        for chk in case.checks.values():
            if chk.needs_peer and not cfg.peer_out_dir:
                skipped.append(f"{case.id}:{chk.name} (needs a peer build)")
                continue
            name = f"{case.id}:check:{chk.name}"
            cmd = " ".join(_cmake_quote(x) for x in [*base, "check", *cfg_args, case.id, chk.name])
            runs = chk.runs or list(case.runs)
            labels = ";".join([chk.tier, *case.labels, "check"])
            fixtures = ";".join(f"{case.id}:{r}" for r in runs)
            lines.append(f"add_test(NAME {_cmake_quote(name)} COMMAND {cmd})\n")
            lines.append(
                f"set_tests_properties({_cmake_quote(name)} PROPERTIES"
                f" LABELS {_cmake_quote(labels)} TIMEOUT 300"
                f" FIXTURES_REQUIRED {_cmake_quote(fixtures)})\n")
            n_tests += 1
    Path(a.out).write_text("".join(lines))
    print(f"sw4test: registered {n_tests} tests ({cfg.precision}, features {cfg.features})")
    for s in skipped:
        print(f"sw4test: skipped {s}")
    return 0


def cmd_run(a) -> int:
    from .runner import execute

    cfg = Config.load(a.config)
    case = find_case(cfg.cases_dir, a.case)
    return execute(cfg, case, case.runs[a.run])


def cmd_check(a) -> int:
    from .checks import run_check

    cfg = Config.load(a.config)
    case = find_case(cfg.cases_dir, a.case)
    chk = case.checks[a.check]
    try:
        ok = run_check(cfg, case, chk)
    except Exception:
        traceback.print_exc()
        ok = False
    print("PASS" if ok else "FAIL")
    return 0 if ok else 1


def cmd_bless(a) -> int:
    """Rewrite goldens for matching cases from the outputs already in out_dir."""
    from .checks import BLESS, Ctx

    cfg = Config.load(a.config)
    pats = a.cases or ["*"]
    n = 0
    for case in load_cases(cfg.cases_dir):
        if not any(fnmatch.fnmatch(case.id, p) for p in pats):
            continue
        for chk in case.checks.values():
            fn = BLESS.get(chk.kind)
            if fn is None:
                continue
            ctx = Ctx(cfg, case, chk)
            try:
                data = fn(ctx)
            except FileNotFoundError as e:
                print(f"skip {case.id}:{chk.name}: {e}")
                continue
            data["meta"] = {
                "precision": cfg.precision,
                "blessed_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "git": _git_describe(cfg.source_dir),
                "sw4": cfg.sw4,
            }
            ctx.golden_path.parent.mkdir(parents=True, exist_ok=True)
            ctx.golden_path.write_text(json.dumps(data, indent=1, sort_keys=True) + "\n")
            print(f"blessed {ctx.golden_path.relative_to(cfg.source_dir)}")
            n += 1
    print(f"{n} goldens written")
    return 0


def _git_describe(src: str) -> str:
    import subprocess

    try:
        return subprocess.run(["git", "-C", src, "describe", "--always", "--dirty"],
                              capture_output=True, text=True).stdout.strip()
    except OSError:
        return "unknown"


def cmd_crosscheck(a) -> int:
    """Run the peer (float-vs-double) checks against two output trees, outside ctest.

    CI builds each precision in its own job; this job downloads both tests/out
    trees and compares them."""
    from .checks import run_check

    cfg = Config.load(a.config) if a.config else Config(
        sw4="", precision=a.precision, features=["hdf5", "proj"], source_dir=a.source_dir,
        out_dir=a.out_dir, mpiexec="mpiexec")
    cfg.out_dir = a.out_dir
    cfg.peer_out_dir = a.peer_out_dir
    cfg.precision, cfg.peer_precision = a.precision, a.peer_precision
    ok = True
    for case in load_cases(cfg.cases_dir):
        for chk in case.checks.values():
            if not chk.needs_peer:
                continue
            print(f"== {case.id}:{chk.name}")
            try:
                good = run_check(cfg, case, chk)
            except FileNotFoundError as e:
                print(f"FAIL: {e}")
                good = False
            print("PASS" if good else "FAIL")
            ok &= good
    return 0 if ok else 1


def cmd_list(a) -> int:
    cfg = Config.load(a.config)
    for case in load_cases(cfg.cases_dir):
        runs = ", ".join(f"{r.name}[{r.tier},{r.ranks}r]" for r in case.runs.values())
        checks = ", ".join(f"{c.name}[{c.kind},{c.tier}]" for c in case.checks.values())
        print(f"{case.id}: runs {runs}; checks {checks}")
    return 0


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    p = argparse.ArgumentParser(prog="sw4test")
    sub = p.add_subparsers(dest="cmd", required=True)

    c = sub.add_parser("configure")
    c.add_argument("--out", required=True)
    c.add_argument("--sw4", required=True)
    c.add_argument("--precision", choices=["double", "float"], required=True)
    c.add_argument("--features", default="")
    c.add_argument("--source-dir", required=True)
    c.add_argument("--out-dir", required=True)
    c.add_argument("--mpiexec", default="mpiexec")
    c.add_argument("--numproc-flag", default="-n")
    c.add_argument("--mpi-preflags", default="")
    c.add_argument("--uv", default="uv")
    c.add_argument("--peer-out-dir", default="")
    c.add_argument("--peer-precision", default="")
    c.set_defaults(fn=cmd_configure)

    for name, fn in (("cmake", cmd_cmake), ("list", cmd_list)):
        s = sub.add_parser(name)
        s.add_argument("--config", required=True)
        if name == "cmake":
            s.add_argument("--out", required=True)
        s.set_defaults(fn=fn)

    r = sub.add_parser("run")
    r.add_argument("--config", required=True)
    r.add_argument("case")
    r.add_argument("run")
    r.set_defaults(fn=cmd_run)

    k = sub.add_parser("check")
    k.add_argument("--config", required=True)
    k.add_argument("case")
    k.add_argument("check")
    k.set_defaults(fn=cmd_check)

    x = sub.add_parser("crosscheck", help="float-vs-double checks between two output trees")
    x.add_argument("--config", default="")
    x.add_argument("--source-dir", default=str(Path(__file__).resolve().parents[4]))
    x.add_argument("--out-dir", required=True, help="tests/out of the first build")
    x.add_argument("--peer-out-dir", required=True, help="tests/out of the other-precision build")
    x.add_argument("--precision", default="float")
    x.add_argument("--peer-precision", default="double")
    x.set_defaults(fn=cmd_crosscheck)

    b = sub.add_parser("bless")
    b.add_argument("--config", required=True)
    b.add_argument("cases", nargs="*", help="case id globs, e.g. 'mms/*'")
    b.set_defaults(fn=cmd_bless)

    a = p.parse_args(argv)
    return a.fn(a)
